static const char index_1[] = "<!DOCTYPE html>";
static const char index_2[] = "<html>";
static const char index_3[] = "<head>";
static const char index_4[] = "<meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8""/>";
static const char index_5[] = "<title>STM32F746DISCO</title>";
static const char index_6[] = "</head>";
static const char index_7[] = "<body>";
static const char index_8[] = "<!-- Feel free to change this text here -->";
static const char index_9[] = "<p>";
static const char index_10[] = "Fork me? Fork you, @octocat!";
static const char index_11[] = "</p>";
static const char index_12[] = "<p>";
static const char index_13[] = "Sean made a change";
static const char index_14[] = "</p>";
static const char index_15[] = "</body>";
static const char index_16[] = "</html>";
